In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [12]:
# from google.colab import drive
# drive.mount('/content/drive')
df = pd.read_csv('Fraud_Detection.csv')

In [13]:

# df = pd.read_csv('/content/drive/MyDrive/Photos/PS_20174392719_1491204439457_log.csv')


In [14]:
df.head()

step      type    amount     nameOrig  oldbalanceOrg  newbalanceOrig  \
0     1   PAYMENT   9839.64  C1231006815       170136.0       160296.36   
1     1   PAYMENT   1864.28  C1666544295        21249.0        19384.72   
2     1  TRANSFER    181.00  C1305486145          181.0            0.00   
3     1  CASH_OUT    181.00   C840083671          181.0            0.00   
4     1   PAYMENT  11668.14  C2048537720        41554.0        29885.86   

      nameDest  oldbalanceDest  newbalanceDest  isFraud  isFlaggedFraud  
0  M1979787155             0.0             0.0        0               0  
1  M2044282225             0.0             0.0        0               0  
2   C553264065             0.0             0.0        1               0  
3    C38997010         21182.0             0.0        1               0  
4  M1230701703             0.0             0.0        0               0

In [15]:
df.columns

Index(['step', 'type', 'amount', 'nameOrig', 'oldbalanceOrg', 'newbalanceOrig',
       'nameDest', 'oldbalanceDest', 'newbalanceDest', 'isFraud',
       'isFlaggedFraud'],
      dtype='object')

In [16]:
print(len(df.columns))


11


In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6362620 entries, 0 to 6362619
Data columns (total 11 columns):
 #   Column          Dtype  
---  ------          -----  
 0   step            int64  
 1   type            object 
 2   amount          float64
 3   nameOrig        object 
 4   oldbalanceOrg   float64
 5   newbalanceOrig  float64
 6   nameDest        object 
 7   oldbalanceDest  float64
 8   newbalanceDest  float64
 9   isFraud         int64  
 10  isFlaggedFraud  int64  
dtypes: float64(5), int64(3), object(3)
memory usage: 534.0+ MB


In [19]:
df.isnull().sum()

step              0
type              0
amount            0
nameOrig          0
oldbalanceOrg     0
newbalanceOrig    0
nameDest          0
oldbalanceDest    0
newbalanceDest    0
isFraud           0
isFlaggedFraud    0
dtype: int64

In [20]:
df.head(20)

step      type     amount     nameOrig  oldbalanceOrg  newbalanceOrig  \
0      1   PAYMENT    9839.64  C1231006815      170136.00       160296.36   
1      1   PAYMENT    1864.28  C1666544295       21249.00        19384.72   
2      1  TRANSFER     181.00  C1305486145         181.00            0.00   
3      1  CASH_OUT     181.00   C840083671         181.00            0.00   
4      1   PAYMENT   11668.14  C2048537720       41554.00        29885.86   
5      1   PAYMENT    7817.71    C90045638       53860.00        46042.29   
6      1   PAYMENT    7107.77   C154988899      183195.00       176087.23   
7      1   PAYMENT    7861.64  C1912850431      176087.23       168225.59   
8      1   PAYMENT    4024.36  C1265012928        2671.00            0.00   
9      1     DEBIT    5337.77   C712410124       41720.00        36382.23   
10     1     DEBIT    9644.94  C1900366749        4465.00            0.00   
11     1   PAYMENT    3099.97   C249177573       20771.00        17671.03   
12     1   PAYMENT    2560.74  C1648232591        5070.00         2509.26   
13     1   PAYMENT   11633.76  C1716932897       10127.00            0.00   
14     1   PAYMENT    4098.78  C1026483832      503264.00       499165.22   
15     1  CASH_OUT  229133.94   C905080434       15325.00            0.00   
16     1   PAYMENT    1563.82   C761750706         450.00            0.00   
17     1   PAYMENT    1157.86  C1237762639       21156.00        19998.14   
18     1   PAYMENT     671.64  C2033524545       15123.00        14451.36   
19     1  TRANSFER  215310.30  C1670993182         705.00            0.00   

       nameDest  oldbalanceDest  newbalanceDest  isFraud  isFlaggedFraud  
0   M1979787155             0.0            0.00        0               0  
1   M2044282225             0.0            0.00        0               0  
2    C553264065             0.0            0.00        1               0  
3     C38997010         21182.0            0.00        1               0  
4   M1230701703             0.0            0.00        0               0  
5    M573487274             0.0            0.00        0               0  
6    M408069119             0.0            0.00        0               0  
7    M633326333             0.0            0.00        0               0  
8   M1176932104             0.0            0.00        0               0  
9    C195600860         41898.0        40348.79        0               0  
10   C997608398         10845.0       157982.12        0               0  
11  M2096539129             0.0            0.00        0               0  
12   M972865270             0.0            0.00        0               0  
13   M801569151             0.0            0.00        0               0  
14  M1635378213             0.0            0.00        0               0  
15   C476402209          5083.0        51513.44        0               0  
16  M1731217984             0.0            0.00        0               0  
17  M1877062907             0.0            0.00        0               0  
18   M473053293             0.0            0.00        0               0  
19  C1100439041         22425.0            0.00        0               0

In [21]:

df = df.drop('step', axis=1)
df

type      amount     nameOrig  oldbalanceOrg  newbalanceOrig  \
0         PAYMENT     9839.64  C1231006815      170136.00       160296.36   
1         PAYMENT     1864.28  C1666544295       21249.00        19384.72   
2        TRANSFER      181.00  C1305486145         181.00            0.00   
3        CASH_OUT      181.00   C840083671         181.00            0.00   
4         PAYMENT    11668.14  C2048537720       41554.00        29885.86   
...           ...         ...          ...            ...             ...   
6362615  CASH_OUT   339682.13   C786484425      339682.13            0.00   
6362616  TRANSFER  6311409.28  C1529008245     6311409.28            0.00   
6362617  CASH_OUT  6311409.28  C1162922333     6311409.28            0.00   
6362618  TRANSFER   850002.52  C1685995037      850002.52            0.00   
6362619  CASH_OUT   850002.52  C1280323807      850002.52            0.00   

            nameDest  oldbalanceDest  newbalanceDest  isFraud  isFlaggedFraud  
0        M1979787155            0.00            0.00        0               0  
1        M2044282225            0.00            0.00        0               0  
2         C553264065            0.00            0.00        1               0  
3          C38997010        21182.00            0.00        1               0  
4        M1230701703            0.00            0.00        0               0  
...              ...             ...             ...      ...             ...  
6362615   C776919290            0.00       339682.13        1               0  
6362616  C1881841831            0.00            0.00        1               0  
6362617  C1365125890        68488.84      6379898.11        1               0  
6362618  C2080388513            0.00            0.00        1               0  
6362619   C873221189      6510099.11      7360101.63        1               0  

[6362620 rows x 10 columns]

In [22]:

df = df.drop('isFlaggedFraud', axis=1)
df

type      amount     nameOrig  oldbalanceOrg  newbalanceOrig  \
0         PAYMENT     9839.64  C1231006815      170136.00       160296.36   
1         PAYMENT     1864.28  C1666544295       21249.00        19384.72   
2        TRANSFER      181.00  C1305486145         181.00            0.00   
3        CASH_OUT      181.00   C840083671         181.00            0.00   
4         PAYMENT    11668.14  C2048537720       41554.00        29885.86   
...           ...         ...          ...            ...             ...   
6362615  CASH_OUT   339682.13   C786484425      339682.13            0.00   
6362616  TRANSFER  6311409.28  C1529008245     6311409.28            0.00   
6362617  CASH_OUT  6311409.28  C1162922333     6311409.28            0.00   
6362618  TRANSFER   850002.52  C1685995037      850002.52            0.00   
6362619  CASH_OUT   850002.52  C1280323807      850002.52            0.00   

            nameDest  oldbalanceDest  newbalanceDest  isFraud  
0        M1979787155            0.00            0.00        0  
1        M2044282225            0.00            0.00        0  
2         C553264065            0.00            0.00        1  
3          C38997010        21182.00            0.00        1  
4        M1230701703            0.00            0.00        0  
...              ...             ...             ...      ...  
6362615   C776919290            0.00       339682.13        1  
6362616  C1881841831            0.00            0.00        1  
6362617  C1365125890        68488.84      6379898.11        1  
6362618  C2080388513            0.00            0.00        1  
6362619   C873221189      6510099.11      7360101.63        1  

[6362620 rows x 9 columns]

Encoding
1. label encoding
2. one hot encoding


In [23]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder


In [24]:
le = LabelEncoder()
df['type'] = le.fit_transform(df['type'])


In [25]:
df.head(10)

type    amount     nameOrig  oldbalanceOrg  newbalanceOrig     nameDest  \
0     3   9839.64  C1231006815      170136.00       160296.36  M1979787155   
1     3   1864.28  C1666544295       21249.00        19384.72  M2044282225   
2     4    181.00  C1305486145         181.00            0.00   C553264065   
3     1    181.00   C840083671         181.00            0.00    C38997010   
4     3  11668.14  C2048537720       41554.00        29885.86  M1230701703   
5     3   7817.71    C90045638       53860.00        46042.29   M573487274   
6     3   7107.77   C154988899      183195.00       176087.23   M408069119   
7     3   7861.64  C1912850431      176087.23       168225.59   M633326333   
8     3   4024.36  C1265012928        2671.00            0.00  M1176932104   
9     2   5337.77   C712410124       41720.00        36382.23   C195600860   

   oldbalanceDest  newbalanceDest  isFraud  
0             0.0            0.00        0  
1             0.0            0.00        0  
2             0.0            0.00        1  
3         21182.0            0.00        1  
4             0.0            0.00        0  
5             0.0            0.00        0  
6             0.0            0.00        0  
7             0.0            0.00        0  
8             0.0            0.00        0  
9         41898.0        40348.79        0

label for:
1 - CASH OUT
2 - DEBIT
3 - PAYMENT
4 - TRANSFER


In [26]:
df = df.drop('nameOrig', axis=1)
df

type      amount  oldbalanceOrg  newbalanceOrig     nameDest  \
0           3     9839.64      170136.00       160296.36  M1979787155   
1           3     1864.28       21249.00        19384.72  M2044282225   
2           4      181.00         181.00            0.00   C553264065   
3           1      181.00         181.00            0.00    C38997010   
4           3    11668.14       41554.00        29885.86  M1230701703   
...       ...         ...            ...             ...          ...   
6362615     1   339682.13      339682.13            0.00   C776919290   
6362616     4  6311409.28     6311409.28            0.00  C1881841831   
6362617     1  6311409.28     6311409.28            0.00  C1365125890   
6362618     4   850002.52      850002.52            0.00  C2080388513   
6362619     1   850002.52      850002.52            0.00   C873221189   

         oldbalanceDest  newbalanceDest  isFraud  
0                  0.00            0.00        0  
1                  0.00            0.00        0  
2                  0.00            0.00        1  
3              21182.00            0.00        1  
4                  0.00            0.00        0  
...                 ...             ...      ...  
6362615            0.00       339682.13        1  
6362616            0.00            0.00        1  
6362617        68488.84      6379898.11        1  
6362618            0.00            0.00        1  
6362619      6510099.11      7360101.63        1  

[6362620 rows x 8 columns]

In [27]:
df = df.drop('nameDest',axis=1)
df

type      amount  oldbalanceOrg  newbalanceOrig  oldbalanceDest  \
0           3     9839.64      170136.00       160296.36            0.00   
1           3     1864.28       21249.00        19384.72            0.00   
2           4      181.00         181.00            0.00            0.00   
3           1      181.00         181.00            0.00        21182.00   
4           3    11668.14       41554.00        29885.86            0.00   
...       ...         ...            ...             ...             ...   
6362615     1   339682.13      339682.13            0.00            0.00   
6362616     4  6311409.28     6311409.28            0.00            0.00   
6362617     1  6311409.28     6311409.28            0.00        68488.84   
6362618     4   850002.52      850002.52            0.00            0.00   
6362619     1   850002.52      850002.52            0.00      6510099.11   

         newbalanceDest  isFraud  
0                  0.00        0  
1                  0.00        0  
2                  0.00        1  
3                  0.00        1  
4                  0.00        0  
...                 ...      ...  
6362615       339682.13        1  
6362616            0.00        1  
6362617      6379898.11        1  
6362618            0.00        1  
6362619      7360101.63        1  

[6362620 rows x 7 columns]

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6362620 entries, 0 to 6362619
Data columns (total 7 columns):
 #   Column          Dtype  
---  ------          -----  
 0   type            int32  
 1   amount          float64
 2   oldbalanceOrg   float64
 3   newbalanceOrig  float64
 4   oldbalanceDest  float64
 5   newbalanceDest  float64
 6   isFraud         int64  
dtypes: float64(5), int32(1), int64(1)
memory usage: 315.5 MB


In [29]:
# prompt: make all columns is X except isfraud

X = df.iloc[:, :-1]


In [30]:
X

type      amount  oldbalanceOrg  newbalanceOrig  oldbalanceDest  \
0           3     9839.64      170136.00       160296.36            0.00   
1           3     1864.28       21249.00        19384.72            0.00   
2           4      181.00         181.00            0.00            0.00   
3           1      181.00         181.00            0.00        21182.00   
4           3    11668.14       41554.00        29885.86            0.00   
...       ...         ...            ...             ...             ...   
6362615     1   339682.13      339682.13            0.00            0.00   
6362616     4  6311409.28     6311409.28            0.00            0.00   
6362617     1  6311409.28     6311409.28            0.00        68488.84   
6362618     4   850002.52      850002.52            0.00            0.00   
6362619     1   850002.52      850002.52            0.00      6510099.11   

         newbalanceDest  
0                  0.00  
1                  0.00  
2                  0.00  
3                  0.00  
4                  0.00  
...                 ...  
6362615       339682.13  
6362616            0.00  
6362617      6379898.11  
6362618            0.00  
6362619      7360101.63  

[6362620 rows x 6 columns]

In [31]:

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_scaled


array([[ 9.52399323e-01, -2.81559923e-01, -2.29810037e-01,
        -2.37621696e-01, -3.23813895e-01, -3.33411405e-01],
       [ 9.52399323e-01, -2.94767262e-01, -2.81359380e-01,
        -2.85812295e-01, -3.23813895e-01, -3.33411405e-01],
       [ 1.69307616e+00, -2.97554804e-01, -2.88653782e-01,
        -2.92441707e-01, -3.23813895e-01, -3.33411405e-01],
       ...,
       [-5.28954357e-01,  1.01539526e+01,  1.89649113e+00,
        -2.92441707e-01, -3.03665258e-01,  1.40302700e+00],
       [ 1.69307616e+00,  1.10976490e+00,  5.58104668e-03,
        -2.92441707e-01, -3.23813895e-01, -3.33411405e-01],
       [-5.28954357e-01,  1.10976490e+00,  5.58104668e-03,
        -2.92441707e-01,  1.59138312e+00,  1.66981230e+00]])

In [32]:
Y = df.iloc[:,-1].values

In [33]:
Y

array([0, 0, 1, ..., 1, 1, 1], dtype=int64)

In [34]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.25,random_state=0)

In [35]:
from sklearn.ensemble import RandomForestClassifier
random_forest = RandomForestClassifier()
random_forest.fit(X_train, Y_train)


RandomForestClassifier()

In [36]:
from sklearn.metrics import accuracy_score
y_pred_random_forest = random_forest.predict(X_test)
acc_random_forest = accuracy_score(Y_test, y_pred_random_forest)
print("Accuracy of Random Forest:", acc_random_forest*100)

Accuracy of Random Forest: 99.96900647846327


In [37]:
random_forest.predict(X_test)

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [38]:
TransType = int(input("Enter the Type of Transaction on Num: "))
Amount = int(input("Enter the Amount: "))
OldBal = int(input("Enter the Old Balance: "))
NewBal = int(input("Enter the New Balance: "))
OldBalDes = int(input("Enter the OldBalDes: "))
NewBalDes = int(input("Enter the NewBalDes: "))

data = [[TransType,Amount,OldBal,NewBal,OldBalDes,NewBalDes]]
result = random_forest.predict(scaler.transform(data))
if result == 1:
  print("The Above Transaction is a Fraud")
else:
  print("The Above Transaction is Not a Fraud")




The Above Transaction is a Fraud


In [39]:
data = [[1,87999,87999,0,0,87999]]
result = random_forest.predict(scaler.transform(data))
if result == 1:
  print("The Above Transaction is a Fraud")
else:
  print("The Above Transaction is Not a Fraud")

The Above Transaction is a Fraud


In [40]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test,y_pred_random_forest);
print("Cofussion Matrix: ")
cm

Cofussion Matrix: 


array([[1588561,      67],
       [    426,    1601]], dtype=int64)

In [44]:
from joblib import dump
dump(random_forest,'model.joblib')

['model.joblib']